[tool.poetry]
name = "cybersecurity-task"
version = "0.1.0"
description = ""
authors = ["Rnbsov <rnbsov@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
cryptography = "^44.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
